KÜTÜPHANELERİ AL

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

DATASET İ DEĞİŞKENE AL

In [2]:
dataset = pd.read_csv("Data.csv")

DATA SET İ GÖRÜNTÜLE

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

BURADA DATASET İÇERİSİNDEKİ VALUE LERİ BAĞIMLI (y) VE BAĞIMSIZ DEĞİŞKEN (X) İMİZE ATADIK
İLOC VERİLERİ SEİÇYOR YANİ VERİNİN LOKASYONUNA GÖRE SEÇİYORUZ 
SEÇTİĞİMİZ VERİLERİ VALUES İLE VALUE OLARAK X VEYA Y İÇERİSİNE ALIYORUZ
[,] VİRGÜLÜN SOLU SATIRLAR, VİRGÜLÜN SAĞI SÜTUNLAR DEMEK OLUYOR. ' : ' İBARESİNİN SOLU BAŞLANGICI SAĞI BİTİŞİ(HARİÇ) İFADE EDER

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #imputer in nasıl çalışacapıı ayarlıyoruz
imputer.fit(X[:,1:3]) #imputeri uyguluyoruz
X[:,1:3] = imputer.transform(X[:,1:3]) # transform ile uyguladığımız fit i dönüştürüyoruz ve uyguladığımız kısıma atıyoruz


In [10]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


BAĞIMSIZ DEĞİŞKENLERİMİZDEKİ KATEGORİK(SINIFSAL/SAYISAL OLMAYAN) VERİLERİ ENCODE ETME YANİ SAYISAL VERİYE ÇEVİRME ÇÜNKİ ALGORİTMAMIZ SAYISAL VERİDEN ANLIYCAK

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough') #OneHotEncoder binary gibi çeviriyor
#Encoderimiz OneHotEncoder, encode edilecek kolon indexi 0 yani ülke isimleri, passtrough iste geri kalan kolonların dpor olmasını yani silinmesini engelliyor
X = np.array(ct.fit_transform(X)) #burada ct olan veriyi fit ve transform ediyoruz.

In [13]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


BAĞIMLI DEĞİŞKENLERİMİZDEKİ KATEGORİK(SINIFSAL/SAYISAL OLMAYAN) VERİLERİ ENCODE ETME YANİ SAYISAL VERİYE ÇEVİRME ÇÜNKİ ALGORİTMAMIZ SAYISAL VERİDEN ANLIYCAK

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # yes no gibi verileri 1 ve 0 olarak çeviriyor.
y = le.fit_transform(y)

In [18]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


ŞİMDİ VERİSETİMİZİ EĞİTİM VE TEST İÇİN İKİYE AYIRACAĞIZ

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
#soldaki değişkenlerin her biri kendi verilerini almoş oluyor
#fonskiyonun içindeki ilk iki parametre arrayler x ve y miz, test_size bunun %20 sini test için ayır kalan %80 ini eğitim/train için ayır demiş oluyoruz
#random_state verileri her defasında karıştır veya karıştırma, eğer int bir değer verirsek tekrar tekrar çalıştırdığımızda karıştırmaz.

In [37]:
print(X_train)

[[0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]


In [25]:
print(X_test)

[[0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [26]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [27]:
print(y_test)

[0 1]


ÖZNİTELİK ÖLÇEKLEME / FEATURE SCALING 
bazı algoritamalar birbirinden çok uzak farklı verileri istemiyor
yani verileri belli bir aralığa sıkıştırmamızı istiyor mesela 0-1 arasında sayılar istiyor
bir anlamda standartlaştırmış gibi oluyor
burada verilerimizin değeri değişmiyor çünkü bunu oranlayıp sıkıştırıyor yani scale ediyor.

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 7:] = sc.fit_transform(X_train[:, 7:]) # ilk 3 kolon zaten 1 ve sıfırlardan oluşuyor onları scale etmemize gerek yok
X_test[:, 7:] = sc.transform(X_test[:, 7:])   # o nedenle sadece scale edilmesi  gereken verileri scale ediyoruz.


In [45]:
print(X_train)

[[0.0 1.0 0.0 1.0 0.0 0.0 1.2909944487358056 -0.19159184384578554
  -1.0781259408412427]
 [0.0 1.0 0.0 1.0 0.0 1.0 -0.7745966692414834 -0.014117293757057846
  -0.07013167641635404]
 [1.0 0.0 1.0 0.0 1.0 0.0 -0.7745966692414834 0.5667085065333239
  0.6335624327104546]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.2909944487358056 -0.3045301939022487
  -0.307866172742979]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.2909944487358056 -1.901801144700799
  -1.4204636155515822]
 [1.0 0.0 1.0 0.0 1.0 0.0 -0.7745966692414834 1.1475343068237056
  1.2326533634535488]
 [0.0 1.0 0.0 1.0 0.0 1.0 -0.7745966692414834 1.4379472069688966
  1.5749910381638883]
 [1.0 0.0 1.0 0.0 1.0 0.0 -0.7745966692414834 -0.7401495441200352
  -0.5646194287757336]]
